
import javax.swing.JFrame;

public class ElevatorSimulation extends JFrame {
    
    //No. of the floor in the simulation
    private int floorNo; 
    
    //the floor control panel
    public ControlPanel control;
    
    // the elevator area
    private Elevator elevator; 
    
    /**
     * Creates new form ElevatorSimulation
     */
    public ElevatorSimulation() {
         /* Create GUI */
        initComponents();
        setLocationRelativeTo(null);
        
        // get the current floor count
        floorNo = Integer.parseInt(numberOfFoors.getValue().toString().trim());
        
        // create a control panel
        control = new ControlPanel(140, 484, floorNo);
        control.setLocation(10, 69);
        
        // create an elevator
        elevator = new Elevator(this, 683, 484, floorNo);
        elevator.setLocation(155, 69);
        
        mainContainer.add(control);
        mainContainer.add(elevator);
        
    }
    
    // set the state 
    public void setState(String message) {
        state.setText(message);
    }

    // return the control
    public ControlPanel getControl() {
        return control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numberOfFoors = new javax.swing.JSpinner();
        startBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elevator Simulator");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator.png"))); // NOI18N

        state.setEditable(false);
        state.setBackground(new java.awt.Color(255, 255, 255));
        state.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Number Of Floors:");

        numberOfFoors.setModel(new javax.swing.SpinnerNumberModel(7, 2, 15, 1));
        numberOfFoors.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberOfFoorsStateChanged(evt);
            }
        });

        startBtn.setBackground(new java.awt.Color(204, 204, 204));
        startBtn.setText("Start Simulation");
        startBtn.setFocusPainted(false);
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        stopBtn.setBackground(new java.awt.Color(204, 204, 204));
        stopBtn.setText("Stop Simulation");
        stopBtn.setFocusPainted(false);
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        quitBtn.setBackground(new java.awt.Color(204, 204, 204));
        quitBtn.setText("Quit Simulation");
        quitBtn.setFocusPainted(false);
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(147, 147, 147)
                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(numberOfFoors, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(mainContainerLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(503, 503, 503)
                .addGroup(mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberOfFoors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn)
                    .addComponent(stopBtn)
                    .addComponent(quitBtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfFoorsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberOfFoorsStateChanged
        
        floorNo = Integer.parseInt(numberOfFoors.getValue().toString());
        elevator.setNumOfFloors(floorNo);
        control.setNumberOfFloors(floorNo);
        
    }//GEN-LAST:event_numberOfFoorsStateChanged

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        elevator.start();
    }//GEN-LAST:event_startBtnActionPerformed

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        elevator.stop();
    }//GEN-LAST:event_stopBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        elevator.stop();
        floorNo = 7; // default is 7 floors
        numberOfFoors.setValue(floorNo);
        elevator.setNumOfFloors(floorNo);
        control.setNumberOfFloors(floorNo);
        
    }//GEN-LAST:event_quitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElevatorSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElevatorSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElevatorSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElevatorSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElevatorSimulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JSpinner numberOfFoors;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton startBtn;
    private javax.swing.JTextField state;
    private javax.swing.JButton stopBtn;
    // End of variables declaration//GEN-END:variables
}
